Implemented business scenario for airline FlyAir.
CPU-Code-School/cpu-biz-scenario pull request #47
Opened 2024-04-05 02:56 UTC by Chanamindy

I did the work, please review and let me know if anything needs to be changed.

2024-04-09 21:35 UTC, AvigailGellis requested changes
Amazing job! See comments and resubmit.

2024-04-09 21:35 UTC, AvigailGellis commented on 3 reports airline.sql
> +select AmountDeparting = count(distinct f.FlightNumber), DepartureDate = datefromparts(year(TimeDeparting), month(TimeDeparting), day(TimeDeparting)), AmountOfPassengers = count(f.FlightNumber)
It isn't necessary to do a datefromparts here, just use the timedeparting column alone.

2024-04-09 21:35 UTC, AvigailGellis commented on 3 reports airline.sql
> +--4)
Destination means the arrival country, not airport.

2024-05-06 02:56 UTC, Chanamindy commented on 1 table airline.sql
> +    FlightNumber varchar(6) not null constraint ck_Flight_flight_number_starts_with_fly_then_3_digits_starting_from_001 check(FlightNumber like 'FLY[0-9][0-9][1-9]'),
Changed it.

2024-05-06 16:52 UTC, AvigailGellis commented
Is this ready for review or you are still in middle of making corrections?

2024-05-07 22:02 UTC, Chanamindy commented
Still making more changes. I dropped the files into the pull request so how do I bring down the comments so I can make changes on my local computer?

2024-05-15 23:43 UTC, Chanamindy commented
"This constraint has to be combined with the constraint about if a passport can be used to fly. Also, don't the instructions say it's valid for 9 years and 6 months? Not 10 years..."

Is the constraint for if it can be used to fly good? All I need to do is combine it with the constraint that it's only valid for 9y and 6m?

The rest of my comments can be reviewed.  I only need to fix this constraint.

2024-05-16 16:21 UTC, AvigailGellis commented
See comment above.

2024-05-22 16:36 UTC, Chanamindy commented
My changes are ready to be marked.

2024-05-23 09:11 UTC, AvigailGellis commented
Sorry for the confusion, please see comment and resubmit. The spec is not crazy clear on this part so it's a bit of a challenge but follow the instructions I wrote and then you will be done.

2024-05-24 01:38 UTC, Chanamindy commented
I don't see the comment. Where is it?

2024-05-26 07:48 UTC, AvigailGellis commented
![image](https://github.com/CPU-Code-School/cpu-biz-scenario/assets/93678714/f2e3b80a-c0d2-4706-8ea9-e08d7bc15466)

2024-07-04 18:29 UTC, Chanamindy commented
Please mark my work with the updated constraints.
Thank you.

2024-07-08 11:26 UTC, AvigailGellis commented
You split it into 2 separate constraints, it must be combined into 1 with or, otherwise it will crash when it doesn't follow one of them.

2024-07-10 18:07 UTC, Chanamindy commented
I'm already so mixed up which two constraints should I combine with a or?

2024-07-14 07:54 UTC, AvigailGellis commented
yes, sorry this spec wasn't so clear about what was needed.

2024-07-24 19:39 UTC, Chanamindy commented
I combined the two constraints.

2024-07-25 06:41 UTC, AvigailGellis commented
Great job! Sorry it took so long!

2024-07-25 06:41 UTC, closed without merging